import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Github, Plus, GitBranch, Upload } from "lucide-react";
import { createRepository, pushToRepository, getCurrentUser } from "@/lib/githubService";
import { toast } from "sonner";
import RepoSelector from "./RepoSelector";

interface GitHubManagerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  code: string;
  projectName: string;
}



export default function GitHubManager({ open, onOpenChange, code, projectName }: GitHubManagerProps) {
  const [selectedRepo, setSelectedRepo] = useState<string>("");
  const [newRepoName, setNewRepoName] = useState(projectName.toLowerCase().replace(/\s+/g, "-"));
  const [isPrivate, setIsPrivate] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [isPushing, setIsPushing] = useState(false);
  const [mode, setMode] = useState<"existing" | "new">("new");
  const [user, setUser] = useState<{ login: string; name: string } | null>(null);

  useEffect(() => {
    if (open) {
      loadUser();
    }
  }, [open]);

  const loadUser = async () => {
    try {
      const userData = await getCurrentUser();
      setUser(userData);
    } catch (error) {
      console.error("Failed to load user:", error);
    }
  };

  const handleCreateRepo = async () => {
    if (!newRepoName.trim()) {
      toast.error("Repository name is required");
      return;
    }

    setIsCreating(true);
    try {
      const repo = await createRepository(newRepoName, `Generated by Arca AI`, isPrivate);
      toast.success(`Repository "${repo.name}" created successfully`);
      await pushCodeToRepo(repo.full_name);
    } catch (error: any) {
      toast.error(error.message || "Failed to create repository");
    } finally {
      setIsCreating(false);
    }
  };

  const handlePushToExisting = async () => {
    if (!selectedRepo) {
      toast.error("Please select a repository");
      return;
    }
    await pushCodeToRepo(selectedRepo);
  };

  const pushCodeToRepo = async (repoFullName: string) => {
    setPushing(true);
    try {
      const [owner, repo] = repoFullName.split("/");
      
      const files = [
        { path: "index.html", content: code },
        { path: "README.md", content: `# ${projectName}\n\nGenerated by Arca AI\n\n## Getting Started\n\nOpen \`index.html\` in your browser to view the application.` }
      ];

      await pushToRepository(owner, repo, files);
      
      // Add to deployment history
      if ((window as any).addDeployment) {
        (window as any).addDeployment({
          repo: repoFullName,
          branch: "main",
          commit: crypto.randomUUID().slice(0, 8),
          status: "success",
          url: `https://github.com/${repoFullName}`
        });
      }
      
      toast.success(`Code pushed to ${repoFullName} successfully`);
      onOpenChange(false);
    } catch (error: any) {
      // Add failed deployment to history
      if ((window as any).addDeployment) {
        (window as any).addDeployment({
          repo: repoFullName,
          branch: "main",
          commit: crypto.randomUUID().slice(0, 8),
          status: "failed"
        });
      }
      toast.error(error.message || "Failed to push code");
    } finally {
      setPushing(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Github className="h-5 w-5" />
            Deploy to GitHub
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          <div className="flex gap-2">
            <Button
              variant={mode === "new" ? "default" : "outline"}
              onClick={() => setMode("new")}
              className="flex-1"
            >
              <Plus className="h-4 w-4 mr-2" />
              New Repository
            </Button>
            <Button
              variant={mode === "existing" ? "default" : "outline"}
              onClick={() => setMode("existing")}
              className="flex-1"
            >
              <GitBranch className="h-4 w-4 mr-2" />
              Existing Repository
            </Button>
          </div>

          {mode === "new" ? (
            <div className="space-y-4">
              <div>
                <Label htmlFor="repo-name">Repository Name</Label>
                <Input
                  id="repo-name"
                  value={newRepoName}
                  onChange={(e) => setNewRepoName(e.target.value)}
                  placeholder="my-awesome-project"
                />
              </div>
              
              <div className="flex items-center justify-between">
                <Label htmlFor="private-repo">Private Repository</Label>
                <Switch
                  id="private-repo"
                  checked={isPrivate}
                  onCheckedChange={setIsPrivate}
                />
              </div>

              <Button
                onClick={handleCreateRepo}
                disabled={isCreating || !newRepoName.trim()}
                className="w-full"
              >
                <Upload className="h-4 w-4 mr-2" />
                {isCreating ? "Creating & Deploying..." : "Create & Deploy"}
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <div>
                <Label>Select Repository</Label>
                <RepoSelector
                  onSelect={setSelectedRepo}
                  selected={selectedRepo}
                />
              </div>

              <Button
                onClick={handlePushToExisting}
                disabled={isPushing || !selectedRepo}
                className="w-full"
              >
                <Upload className="h-4 w-4 mr-2" />
                {isPushing ? "Deploying..." : "Deploy to Repository"}
              </Button>
            </div>
          )}

          {user && (
            <div className="text-xs text-muted-foreground text-center">
              Deploying as {user.name || user.login}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}